### ISSUE TITLE
The whole encryption configuration is null. Have you forgotten to add it to the config section: MessageEncryption Parameter name: config

### ISSUE THREAD

**Issue by jangrimm** [ArtisanCode/SimpleAesEncryption#3]
I set up everything as shown under samples, and this is what my App.config looks like:

`<section name="MessageEncryption" type="ArtisanCode.SimpleAesEncryption.SimpleAesEncryptionConfiguration, ArtisanCode.SimpleAesEncryption" />`

`<MessageEncryption>
    <EncryptionKey KeySize="256" Key="SOMEKEYYOUCANNEVERIMAGINEHAHA"/>
  </MessageEncryption>`

However, the error which is being thrown:

> 
> ---------------------------
> Error
> ---------------------------
> The whole encryption configuration is null. Have you forgotten to add it to the config section: MessageEncryption
> 
> Parameter name: config
> ---------------------------
> OK   
> ---------------------------
> 

I don't understand. It works fine in other projects.

**Comment by jangrimm** [comment]
The solution was to entirely delete the App.config and re-add it to the project. Seems to have messed up something about the file. Works now.

**Comment by Tom-Kuhn** [comment]
Hi Jan,

Looking at the sample provided above, the XML looks fine. (I'm assuming that you omitted the configSections element for breviary, if not then you'll need to add the section into the configSections portion of the config file).

One thing to check is that the whole config file is valid XML and make sure that the code can correctly parse the whole document.

If your config checks out, please let me know and we can think of other solutions.

Tom

**Comment by Tom-Kuhn** [comment]
Thanks for letting me know that you've fixed the issue!

Good luck with the project.
