### ISSUE TITLE
Powershell KeyGen without need to compile exe

### ISSUE THREAD

**Issue by sm-g** [ArtisanCode/SimpleAesEncryption#4]
You may use two powershell lines to generate keys:
```powershell
$container = New-Object System.Security.Cryptography.RijndaelManaged
# defaults
# $container.KeySize = 256
# $container.Mode = CBC
[Convert]::ToBase64String($container.Key)
```

**Comment by Tom-Kuhn** [comment]
Thanks for the tip, I hadn't considered alternate ways to generate new keys.
 
Would you be interested in submitting a pull request adding this information to the readme.md file?
Possibly adding this information under the "Add encryption configuration" section, or create a new "Generating keys" section

**Comment by sm-g** [comment]
I'm too lazy to fork/pull-request, sorry

**Comment by Tom-Kuhn** [comment]
updated README.md with this info
